Ternary baseline
enjoychallenge/pomootskey pull request #96
Opened 2024-01-22 16:42 UTC by index-git

2024-01-23 09:31 UTC, jirik requested changes

2024-01-23 09:31 UTC, jirik commented on features/ternary/ternarySelector.js
> +    const baseOrders = '123'
It can be array of numbers

2024-01-23 09:31 UTC, jirik commented on features/ternary/ternarySelector.js
> +    const variantCharsOrders = cartesian(variantChars, variantOrders)
Currently variantCharsOrders hase only 25 variants, we want 36 (or 35)

2024-01-23 09:31 UTC, jirik commented on features/ternary/ternarySlice.js
> +    keyDown: (state, action) => {
It seems not working, probably because of lower case

2024-01-23 09:31 UTC, jirik commented on features/ternary/ternarySlice.js
> +    paste: (state, action) => {
Když vložím URL, v GUI vidím obdélníky místo otazníků

2024-01-23 09:31 UTC, jirik commented on styles/ternary.module.scss
> +  width: var(--morseInputCharWidth);
use ternaryInputCharWidth instead of morseInputCharWidth

2024-01-23 09:31 UTC, jirik commented on styles/ternary.module.scss
> +  width: var(--morseInputCharWidth);
and so on for other variables

2024-01-23 16:29 UTC, index-git commented on app/decode/ternary.js
> +        part.char = String.fromCharCode('A'.charCodeAt(0) + value)
Nevidím toto sjednocení jako užitečné či přínosné.

2024-01-25 08:14 UTC, jirik approved these changes

2024-01-25 08:17 UTC, merged